defaults:
    - model: default
    - training: cpc

resume: False
checkpoint_dir: checkpoints

mi_weight: 0.01
mi_lr: 3e-4
mi_iters: 5

sampling: sameSeq
train_file: train
valid_file: valid

encoder_lf0_type: no_emb
use_CSMI: True  # use MI between content and speaker
use_CPMI: True  # use MI between content and pitch
use_PSMI: True  # use MI between picth and speaker

use_amp: False # set to True to speed up training