Models:
  - Name: group_fisher_act_finetune_retinanet_r50_fpn_1x_coco
    In Collection: GroupFisher
    Config: configs/pruning/mmdet/group_fisher/retinanet/group_fisher_act_finetune_retinanet_r50_fpn_1x_coco.py
    Weights: https://download.openmmlab.com/mmrazor/v1/pruning/group_fisher/retinanet/act/group_fisher_act_finetune_retinanet_r50_fpn_1x_coco.pth
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.5
  - Name: group_fisher_flops_finetune_retinanet_r50_fpn_1x_coco
    In Collection: GroupFisher
    Config: configs/pruning/mmdet/group_fisher/retinanet/group_fisher_flops_finetune_retinanet_r50_fpn_1x_coco.py
    Weights: https://download.openmmlab.com/mmrazor/v1/pruning/group_fisher/retinanet/flops/group_fisher_flops_finetune_retinanet_r50_fpn_1x_coco.pth
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.6
