# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output
  device: gpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  eval_mode: "retrieval"
  epochs: 128
  print_batch_step: 10
  use_visualdl: False

  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference

  #feature postprocess
  feature_normalize: False
  feature_binarize: "round"

# model architecture
Arch:
  name: "RecModel"
  Backbone:
    name: "VGG19Sigmoid"
    pretrained: True
    class_num: 48
  Head:
    name: "FC"
    class_num: 10
    embedding_size: 48
    
  infer_output_key:  "features"
  infer_add_softmax: "false"

# loss function config for train/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.1
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Piecewise
    learning_rate: 0.01
    decay_epochs: [200]
    values: [0.01, 0.001]

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: ./dataset/cifar10/
      cls_label_path: ./dataset/cifar10/cifar10-2/train.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: 256
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.4914, 0.4822, 0.4465]
            std: [0.2023, 0.1994, 0.2010]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 128
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True

  Eval:
    Query:
      dataset: 
        name: ImageNetDataset
        image_root: ./dataset/cifar10/
        cls_label_path: ./dataset/cifar10/cifar10-2/test.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 1.0/255.0
              mean: [0.4914, 0.4822, 0.4465]
              std: [0.2023, 0.1994, 0.2010]
              order: ''
      sampler:
        name: DistributedBatchSampler
        batch_size: 512
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

    Gallery:
      dataset: 
        name: ImageNetDataset
        image_root: ./dataset/cifar10/
        cls_label_path: ./dataset/cifar10/cifar10-2/database.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 1.0/255.0
              mean: [0.4914, 0.4822, 0.4465]
              std: [0.2023, 0.1994, 0.2010]
              order: ''
      sampler:
        name: DistributedBatchSampler
        batch_size: 512
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

Metric:
  Train:
    - TopkAcc:
        topk: [1, 5]
  Eval:
    - mAP:
    - Precisionk:
        topk: [1, 5]
        
