# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
checkpoint_url: ""
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: GPU
enable_profiling: False

# ==============================================================================
dataset_path: "/cache/data"
ckpt_path: '/cache/data/'
checkpoint: '/cache/data/inceptionv3/inceptionv3-rank3_1-247_1251.ckpt'
ckpt_file: '/cache/data/inceptionv3/inceptionv3-rank3_1-247_1251.ckpt'
onnx_file: ''
resume: ''
is_distributed: False
device_id: 0
platform: 'GPU'
file_name: 'inceptionv3'
file_format: 'MINDIR'
width: 299
height: 299

modelarts_dataset_unzip_name: 'ImageNet_Original'
need_modelarts_dataset_unzip: True
ckpt_save_dir: './ckpt/'
result_path: '' # "result file path"
label_file: '' # "label file"

# Training options
random_seed: 1
work_nums: 8
decay_method: 'cosine'
loss_scale: 1
batch_size: 128
epoch_size: 250
num_classes: 1000
ds_type: 'imagenet'
ds_sink_mode: True
smooth_factor: 0.1
aux_factor: 0.2
lr_init: 0.00004
lr_max: 0.4
lr_end: 0.000004
warmup_epochs: 1
weight_decay: 0.00004
momentum: 0.9
opt_eps: 1.0
keep_checkpoint_max: 10
is_save_on_master: 0
dropout_keep_prob: 0.5
has_bias: True
amp_level: 'O0'


---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type' 
enable_profiling: 'Whether enable profiling while training, default: False'
file_name: 'output file name.'
file_format: 'file format'

---
device_target: ['Ascend', 'GPU', 'CPU']
file_format: ['AIR', 'ONNX', 'MINDIR']
