# This is the configuration file for yesno dataset.
# Note that this configuration is just for debugging.

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
sampling_rate: 8000      # Sampling rate.
fft_size: 1024           # FFT size.
hop_size: 256            # Hop size.
win_length: null         # Window length.
                         # If set to null, it will be the same as fft_size.
window: "hann"           # Window function.
num_mels: 80             # Number of mel basis.
fmin: 0                  # Minimum freq in mel basis calculation.
fmax: 4000               # Maximum frequency in mel basis calculation.
global_gain_scale: 0.8   # Will be multiplied to all of waveform.
trim_silence: false      # Whether to trim the start and end of silence.
trim_threshold_in_db: 60 # Need to tune carefully if the recording is not good.
trim_frame_size: 1024    # Frame size in trimming.
trim_hop_size: 256       # Hop size in trimming.
format: "hdf5"           # Feature file format. " npy " or " hdf5 " is supported.

###########################################################
#         GENERATOR NETWORK ARCHITECTURE SETTING          #
###########################################################
generator_type: "StyleMelGANGenerator" # Generator type.
generator_params:
    in_channels: 128
    aux_channels: 80
    channels: 64
    out_channels: 1
    kernel_size: 9
    dilation: 2
    bias: True
    noise_upsample_scales: [4, 2, 2, 2]
    noise_upsample_activation: "LeakyReLU"
    noise_upsample_activation_params:
        negative_slope: 0.2
    upsample_scales: [2, 2, 2, 2, 2, 2, 2, 2, 1]
    upsample_mode: "nearest"
    gated_function: "softmax"
    use_weight_norm: True

###########################################################
#       DISCRIMINATOR NETWORK ARCHITECTURE SETTING        #
###########################################################
discriminator_type: "StyleMelGANDiscriminator" # Discriminator type.
discriminator_params:
    repeats: 4
    window_sizes: [512, 1024, 2048, 4096]
    pqmf_params:
        - [1, None, None, None]
        - [2, 62, 0.26700, 9.0]
        - [4, 62, 0.14200, 9.0]
        - [8, 62, 0.07949, 9.0]
    discriminator_params:
        out_channels: 1
        kernel_sizes: [5, 3]
        channels: 16
        max_downsample_channels: 512
        bias: True
        downsample_scales: [4, 4, 4, 1]
        nonlinear_activation: "LeakyReLU"
        nonlinear_activation_params:
            negative_slope: 0.2
    use_weight_norm: True

###########################################################
#                   STFT LOSS SETTING                     #
###########################################################
stft_loss_params:
    fft_sizes: [1024, 2048, 512]  # List of FFT size for STFT-based loss.
    hop_sizes: [120, 240, 50]     # List of hop size for STFT-based loss
    win_lengths: [600, 1200, 240] # List of window length for STFT-based loss.
    window: "hann_window"         # Window function for STFT-based loss
lambda_aux: 1.0                   # Loss balancing coefficient for aux loss.

###########################################################
#               ADVERSARIAL LOSS SETTING                  #
###########################################################
lambda_adv: 1.0 # Loss balancing coefficient for adv loss.
generator_adv_loss_params:
    average_by_discriminators: false # Whether to average loss by #discriminators.
    loss_type: hinge                 # Loss function type ("mse" or "hinge").
discriminator_adv_loss_params:
    average_by_discriminators: false # Whether to average loss by #discriminators.
    loss_type: hinge                 # Loss function type ("mse" or "hinge").

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 2               # Batch size.
batch_max_steps: 8192       # Length of each audio in batch. Make sure dividable by hop_size.
pin_memory: true            # Whether to pin memory in Pytorch DataLoader.
num_workers: 2              # Number of workers in Pytorch DataLoader.
remove_short_samples: false # Whether to remove samples the length of which are less than batch_max_steps.
allow_cache: true           # Whether to allow cache in dataset. If true, it requires cpu memory.

###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
generator_optimizer_type: Adam
generator_optimizer_params:
    lr: 0.0001              # Generator's learning rate.
    betas: [0.5, 0.9]
    weight_decay: 0.0       # Generator's weight decay coefficient.
generator_scheduler_params:
    step_size: 200000       # Generator's scheduler step size.
    gamma: 0.5              # Generator's scheduler gamma.
                            # At each step size, lr will be multiplied by this parameter.
generator_grad_norm: -1     # Generator's gradient norm.
discriminator_optimizer_type: Adam
discriminator_optimizer_params:
    lr: 0.00005             # Discriminator's learning rate.
    betas: [0.5, 0.9]
    weight_decay: 0.0       # Discriminator's weight decay coefficient.
discriminator_scheduler_params:
    step_size: 200000       # Discriminator's scheduler step size.
    gamma: 0.5              # Discriminator's scheduler gamma.
                            # At each step size, lr will be multiplied by this parameter.
discriminator_grad_norm: -1 # Discriminator's gradient norm.

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
discriminator_train_start_steps: 5 # Number of steps to start to train discriminator.
train_max_steps: 10                # Number of training steps.
save_interval_steps: 5             # Interval steps to save checkpoint.
eval_interval_steps: 5             # Interval steps to evaluate the network.
log_interval_steps: 5              # Interval steps to record the training log.

###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 4  # Number of results to be saved as intermediate results.
